# Generated by Django 4.2.23 on 2025-08-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
