# Generated by Django 4.2.23 on 2025-09-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='students', to='academics.subject'),
        ),
    ]
